# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

  desc "Generates Xcode project."
  lane :generate_xcode_project do
    spm(command: "generate-xcodeproj")
  end

  desc "Generates documentation"
  lane :generate_docs do
    generate_xcode_project
    brew(command: "install sourcekitten")
    library_docs=`sourcekitten doc --module-name ErrorAssertions -- -project ../ErrorAssertions.xcodeproj`
    testhelpers_docs=`sourcekitten doc --module-name ErrorAssertionExpectations  -- -project ../ErrorAssertions.xcodeproj`
    combined_docs=library_docs[0..-3] + ', ' + testhelpers_docs[1..-1]
    IO.write('library_docs.json', library_docs)
    IO.write('testhelpers_docs.json', testhelpers_docs)
    IO.write('combined_docs.json', combined_docs)
    jazzy(config: ".jazzy.yml")
  end
