name: tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  linux:
    strategy:
      fail-fast: false
      matrix:
        image: 
          - "swift:5.1"
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Debug Build
      run: swift build -c debug
    - name: Debug Test
      run: swift test -c debug

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Debug Build
      run: swift build -c debug
    - name: Debug Test
      run: swift test -c debug
